### ISSUE TITLE
не работает каараван фионы

### ISSUE THREAD

**Issue by SneshanaPandarenka** [alexkulya/magic_storm_issues#10]
Не работают оба квеста с фионой - чувачков я нашла, квесты их выполнила, а вот их самих у фионы нету... Видимо из за этого.  У повозки к тому же мотыляет оглоблю..

https://ru.wowhead.com/quest=27373/onward-to-lights-hope-chapel

https://ru.wowhead.com/quest=27448/the-trek-continues
![WoWScrnShot_090419_144850](https://user-images.githubusercontent.com/54682071/64251290-632a0480-cf42-11e9-8e93-3603eecc2949.jpg)

**Comment by MENZ411** [comment]
https://youtu.be/SfTY8wSwpm8
:)

**Comment by SneshanaPandarenka** [comment]
> https://youtu.be/SfTY8wSwpm8
> :)

погоди... то есть брать эти амулеты у повозки не надо было?

**Comment by MENZ411** [comment]
> погоди... то есть брать эти амулеты у повозки не надо было?

нет, это демонстрация моего фикса

данный квест по моему только на одном сервере работает, а в сборках вообще нигде

**Comment by SneshanaPandarenka** [comment]
Даа... С караванами беда везде... не хочут они робить...

**Comment by alexkulya** [comment]
Скрипт реализован. Осталось исправить мелкие недочеты.

**Comment by alexkulya** [comment]
Исправлено.
