### ISSUE TITLE
не робит квест подготовка големов

### ISSUE THREAD

**Issue by SneshanaPandarenka** [alexkulya/magic_storm_issues#14]
Не работает квест подготовка големов wow, големы не отвечают на реплики.  Пылающие степи, узкоклинье.

https://ru.wowhead.com/quest=28227/golem-training

![WoWScrnShot_090819_141208](https://user-images.githubusercontent.com/54682071/64485741-67119b80-d24e-11e9-8884-1a10e97a80cf.jpg)

**Comment by alexkulya** [comment]
Исправлено.
