### ISSUE TITLE
Украденные письма(темнолесье)

### ISSUE THREAD

**Issue by SneshanaPandarenka** [alexkulya/magic_storm_issues#4]
Письма видны только в гм-режиме.... В обычном нету.. 

https://ru.wowhead.com/quest=26667/%D1%83%D0%BA%D1%80%D0%B0%D0%B4%D0%B5%D0%BD%D0%BD%D1%8B%D0%B5-%D0%BF%D0%B8%D1%81%D1%8C%D0%BC%D0%B0

![431](https://user-images.githubusercontent.com/54682071/64023984-9d229180-cb63-11e9-8a76-25b2fd04814d.jpg)

**Comment by alexkulya** [comment]
Исправлено.
